algoritmo "01"
// Disciplina :  Lógica de programação com javascript
// Professor : Jailson
// Descrição : Ler uma temperatura em graus Celsius e apresentar
// Autor :   Victor melo da costa
// Data :  02/09/2026
// Seção de Declarações 
var
   a : inteiro
   b : inteiro
   c : inteiro
inicio
// Seção de Comandos 

a <- 10
b <- 20

c <- a
a <- b
b <- c
escreval ( "A: ",a, "B: ",b)
fimalgoritmo
