algoritmo "05"
// Disciplina :  Lógica de programação com javascript
// Professor : Jailson
// Descrição : Ler uma temperatura em graus Celsius e apresentar
// Autor :   Victor melo da costa
// Data :  02/09/2026
// Seção de Declarações 
var
   c : inteiro
   d : inteiro
inicio
// Seção de Comandos 

escreval("antecessor")
escreval("digite um numero")
leia(c)
d <- c -1



escreval ( "o antecessor do seu numero é  ",d)
fimalgoritmo
