algoritmo "06"
// Disciplina :  Lógica de programação com javascript
// Professor : Jailson
// Descrição : Ler uma temperatura em graus Celsius e apresentar
// Autor :   Victor melo da costa
// Data :  02/09/2026
// Seção de Declarações 
var
   base : inteiro
   altura : inteiro
   resultado : real
inicio
// Seção de Comandos 

escreval("qual o tamanho da base ? ")
leia(base)
escreval("qual o tamanho da altura")
leia(altura)
resultado <- base * altura
escreval("a area do retangulo é : ?", resultado)





fimalgoritmo
