algoritmo "07"
// disciplima :Lógica de programação com javascript
// professor : Jailson costa dos santos
// Autor : Victor melo
// Data : 21/09/2026
// Seção de Declarações 
var
 anos : inteiro
 meses : inteiro
 dias : inteiro
 totalDias : inteiro
inicio
// Seção de Comandos 
escreval("digite quantos anos voce tem ?")
leia(anos)

escreval("digite quantos  meses voce tem ?")
leia(meses)

escreval("digite quantos dias voce tem ?")
leia(dias)

totalDias <-  (anos * 365) + (meses * 30)  + dias

escreval("o total de dias vividos são ", totalDias  )


 


fimalgoritmo
