algoritmo "010"
// disciplima :Lógica de programação com javascript
// professor : Jailson costa dos santos
// Autor : Victor melo
// Data : 21/09/2026
// Seção de Declarações 
var
 carro : real
 distribuidor : real
 impostos : real
 valorTotalCarro : real

inicio
// Seção de Comandos 

distribuidor <- 28
impostos <- 45
escreval("digite o valor do seu carro ?")
leia(carro)



 valorTotalCarro <-  carro + ((distribuidor  * carro )/100 )   + ((impostos * carro)/100)

escreval("o valor total do carro ficou   ", valorTotalCarro:0:2 )



fimalgoritmo
