algoritmo "012"
// disciplima :Lógica de programação com javascript
// professor : Jailson costa dos santos
// Autor : Victor melo
// Data : 22/09/2026
// Seção de Declarações 
var
 Fahrenheit : real
 Celsius : real


inicio
// Seção de Comandos 
escreval("qual é a temperatura em Fahrenheit ?")
leia(Fahrenheit)


Celsius <- ((Fahrenheit - 32) * 5) / 9


escreval("o valor em Celsius ficou :  ", Celsius:0:2, "°C" )



fimalgoritmo
