algoritmo "013"
// disciplima :Lógica de programação com javascript
// professor : Jailson costa dos santos
// Autor : Victor melo
// Data : 22/09/2026
// Seção de Declarações 
var
 nota1 : real
 nota2 : real
 nota3 : real

 mediaFinal : real

inicio
// Seção de Comandos 
escreval("qual foi a sua primeira nota  ?")
leia(nota1)

escreval("qual foi a sua primeira nota  ?")
leia(nota2)

escreval("qual foi a sua primeira nota  ?")
leia(nota3)

mediaFinal <- ((nota1 * 2) + (nota2 * 3) + (nota3 * 5)) / 10

escreval("a media do aluno é  :  ", mediaFinal )



fimalgoritmo
