algoritmo "014"

// Disciplina :  Lógica de programação com javascript
// Professor : Jailson
// Descrição : Ler uma temperatura em graus Celsius e apresentar
// Autor :   Victor melo da costa
// Data :  02/09/2026
// Seção de Declarações
var

 valor : inteiro



inicio
// Seção de Comandos
escreval(" qual valor ? : ")
leia(valor)
se valor >10 entao
escreval("o valor é maior que 10 ")
senao
escreval ("o valor Não é maior que 10")
fimse
fimalgoritmo
