algoritmo "018"

// Disciplina :  Lógica de programação com javascript
// Professor : Jailson
// Descrição : Ler uma temperatura em graus Celsius e apresentar
// Autor :   Victor melo da costa
// Data :  02/09/2026
// Seção de Declarações
var
 ano : inteiro
 ano_nasc : inteiro
 resul : inteiro
 

inicio
// Seção de Comandos
escreval("qual ano estamos ")
leia(ano)
escreval("qual o ano de nascimento")
leia(ano_nasc)
resul <- ano - ano_nasc
se resul <16 entao
escreval ("você não esta apto(a) para votar")
senao
escreval("você está apto a votar")
fimse

fimalgoritmo
