algoritmo "020"

// Disciplina :  Lógica de programação com javascript
// Professor : Jailson
// Descrição : Ler uma temperatura em graus Celsius e apresentar
// Autor :   Victor melo da costa
// Data :  02/09/2026
// Seção de Declarações
var
 valor1 : inteiro
 valor2 : inteiro

 

inicio
// Seção de Comandos
escreval(" digite um valor ")
leia(valor1)
escreval("digite um valor")
leia(valor2)

se valor1 < valor2 entao
escreval ( valor1 , valor2)
senao
escreval( valor2 , valor1 )
fimse

fimalgoritmo
