algoritmo "027"

// Disciplina :  Lógica de programação com javascript
// Professor : Jailson
// Descrição : Ler uma temperatura em graus Celsius e apresentar
// Autor :   Victor melo da costa
// Data :  07/09/2026
// Seção de Declarações
var
numero : inteiro

inicio
// Seção de Comandos 
escreval("digite um numero ?")
leia(numero)

se numero >=1 entao
escreval (" o numero é positivo")
senao
se numero = 0 entao
escreval("o numero é zero")
senao
escreval ("o numero é negativo ")
fimse


fimse

fimalgoritmo
