algoritmo "033"
// disciplina : Logica de programacao com javascript
// professor : Jailson costa dos santos
// Autor : Victor melo
// Data : 22/09/2026

var
   valor1 : inteiro
   valor2 : inteiro



inicio

escreval("Digite um numero : ")
leia(valor1)
escreval("Digite outro numero : ")
leia(valor2)



se ( valor1 > valor2)   entao
   escreval("o numero : ", valor1, " É o maior ")
   senao
   se (   valor1 = valor2) entao
   escreval("Números iguais")
   senao
   
   escreval("o numero: ", valor2, " É O maior")
   fimse
fimse


fimalgoritmo
